import type { Metadata } from "next";
import {Exo_2,Share_Tech_Mono} from "next/font/google";
import "./globals.css";


const exo = Exo_2({
  subsets: ["latin"], weight:['400','700'], 
});

const stm = Share_Tech_Mono({
  subsets: ["latin"], weight:['400'], 
});


export const metadata: Metadata = {
  title: "Evaleash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
